### 

POST {{host}}/sign-up HTTP/1.1
Content-Type: application/json

{
  "displayName": "{{displayName}}",
  "handle": "{{handle}}",
  "password": "{{password}}",
  "username": "{{username}}"
}


### 

POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "password": "{{password}}",
  "username": "{{username}}"
}


### 
