CREATE TYPE USER_ROLES AS ENUM ('ROLE_MEMBER', 'ROLE_ADMIN', 'ROLE_INSTRUCTOR');
BEGIN;
ALTER TABLE author ADD COLUMN role USER_ROLES;
UPDATE author SET role = 'ROLE_MEMBER' WHERE role IS NULL;
ALTER TABLE author ALTER COLUMN role SET NOT NULL;
COMMIT;
